config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :cashiers
  resources :events

  get 'site/home', to: "site#home", as: "home"
  get 'site/dados', to: "site#dados", as: "dados"
  get 'inicial/index', to: "inicial#index", as: "index"


  devise_for :admins
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  #devise_scope :user do get "/some/route" => "some_devise_controller"


  authenticated :user do
    root 'site#home', as: :authenticated_root
  end

  authenticated :admin do
    root 'site#secret', as: :authenticated_root2
    #post '/delete_user/:id', to
  end

  root 'inicial#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  layout 'admin_lte_2'
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :start, :end, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.date_select :start, id: :project_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.date_select :end, id: :project_end %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :name, {:include_blank => 'Usuário'}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projetos</h1>
<br>
<% if user_signed_in? %>
  <p>Projetos que você está:</p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start</th>
      <th>End</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <% if user_signed_in? %>
          <% if current_user.name == project.user.name %>
              <td><%= project.name %></td>
              <td><%= project.description %></td>
              <td><%= project.start %></td>
              <td><%= project.end %></td>
              <td><%= project.user.name %></td>
              <td><%= link_to 'Show', project %></td>
            <% if admin_signed_in? %>
              <td><%= link_to 'Edit', edit_project_path(project) %></td>
              <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
            <% end %> 
          <% end %>
        <% end %>
       <%if admin_signed_in?%>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start %></td>
        <td><%= project.end %></td>
        <td><%= project.user.name %></td>
        <td><%= link_to 'Show', project %></td>
        <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <% end %>
       <%end%> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @project.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @project.end %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.name %>
</p>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>